/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fa1_q2;

import javax.swing.JOptionPane;

/**
 *
 * @author rjnkr
 */
public class FA1_Q2_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form FA1_Q2_JFrame
     */
    public FA1_Q2_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblTerm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAmount = new javax.swing.JTextPane();
        rbt5 = new javax.swing.JRadioButton();
        rbt10 = new javax.swing.JRadioButton();
        rbt15 = new javax.swing.JRadioButton();
        CmbType = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCalculate = new javax.swing.JMenuItem();
        jMenuClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invertment Calculator");

        lblName.setText("Customer Name:");

        lblAmount.setText("Enter Amount");

        lblType.setText("Select Type");

        lblTerm.setText("Select Term");

        jScrollPane1.setViewportView(txtName);

        jScrollPane2.setViewportView(txtAmount);

        rbt5.setText("5 Years");
        rbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt5ActionPerformed(evt);
            }
        });

        rbt10.setText("10 Years");
        rbt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt10ActionPerformed(evt);
            }
        });

        rbt15.setText("15 Years");
        rbt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt15ActionPerformed(evt);
            }
        });

        CmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moderate", "Aggressive" }));

        jMenu1.setText("File");

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        jMenuCalculate.setText("Calculate");
        jMenuCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalculateActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCalculate);

        jMenuClear.setText("Clear");
        jMenuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClearActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuClear);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType)
                            .addComponent(lblAmount)
                            .addComponent(lblTerm))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbt15)
                            .addComponent(rbt10)
                            .addComponent(rbt5)
                            .addComponent(CmbType, 0, 212, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmount)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(CmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTerm)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbt10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbt15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalculateActionPerformed
        String name = "";
        double finalAmount,p=0, r = 0, amount = 0;
        int n = 1,t = 0;
        
        name = txtName.getText();
        amount = Double.parseDouble(txtAmount.getText());
        
        if(CmbType.getSelectedIndex()==0){
            r = 0.1;
        }else if(CmbType.getSelectedIndex()==1){
            r = 0.15;
        }
        
        if(rbt5.isSelected()){
            t = 5;
        }else if(rbt10.isSelected()){
            t = 10;
        }else if(rbt15.isSelected()){
            t = 15;
        }
        
        p = amount * (Math.pow(1+(r / n), n*t));
        finalAmount= Math.round(p * 100.0) / 100.0;
        JOptionPane.showMessageDialog(rootPane, "Customer Name: "+name+"\nOriginal Amount: R"+amount+"\n Years Invsted: "+t+ "\nFinal Amount: R"+finalAmount);
        
    }//GEN-LAST:event_jMenuCalculateActionPerformed

    private void jMenuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClearActionPerformed
        txtName.setText("");
        txtAmount.setText("");
        rbt5.setSelected(false);
        rbt10.setSelected(false);
        rbt15.setSelected(false);
    }//GEN-LAST:event_jMenuClearActionPerformed

    private void rbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt5ActionPerformed
        rbt10.setSelected(false);
        rbt15.setSelected(false);
    }//GEN-LAST:event_rbt5ActionPerformed

    private void rbt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt10ActionPerformed
        rbt5.setSelected(false);
        rbt15.setSelected(false);
    }//GEN-LAST:event_rbt10ActionPerformed

    private void rbt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt15ActionPerformed
        rbt5.setSelected(false);
        rbt10.setSelected(false);
    }//GEN-LAST:event_rbt15ActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FA1_Q2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FA1_Q2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FA1_Q2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FA1_Q2_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FA1_Q2_JFrame question2 = new FA1_Q2_JFrame();
                question2.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbType;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCalculate;
    private javax.swing.JMenuItem jMenuClear;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTerm;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton rbt10;
    private javax.swing.JRadioButton rbt15;
    private javax.swing.JRadioButton rbt5;
    private javax.swing.JTextPane txtAmount;
    private javax.swing.JTextPane txtName;
    // End of variables declaration//GEN-END:variables
}
